server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    # 配置gateway网关
    gateway:
      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh   # 路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      registry-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/